config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  devise_for :users
  resources :books
  resources :reservations

  delete "/remove_reservation", to: "pages#remove_reservation"
  get "/user_books", to: "pages#userbooks"
  post "/reserved", to: "pages#reserved"
  get "/make_reservation", to: "pages#make_reservation"
  post "/make_reservation", to: "pages#make_reservation"

  root to: "pages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reservations
    scope :get_available_books, -> { where(id: Reservation.reserved_book) }
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservation
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book

  scope :reservation, -> (user_id) { where("user_id = ?", user_id) }
  scope :reserved_book, -> { all.pluck(:book_id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /books or /books.json
  def index
    @books = Book.all

  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author, :price, :code)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @books = Book.get_available_books
  end

  def show
    @book = Book.find(params[:id])
  end

  def user_reservation
    @reservations = Reservation.reservations(current_user.id)
end

def reserved
    @book = Book.find(params[:book_id])
    @reservation = Reservation.new(
        user_id: current_user.id,
        book_id: params[:book_id]
        )
    if @reservation.save!
    else
    end
end

def remove_reserve
    @reservation = Reservation.find(params[:id])
    @reservation.destroy!
end

end 

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
    before_action :set_reservation, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

  def index
    @reservations = Reservation.all
    end

  def new
    @reservation = Reservation.new
  end

  def show
  end

  def edit
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save!
    else
    end
  end

  def update
    if @reservation.update!(reservation_params)
    else
    end
  end

  def destroy
    @reservation.destroy!
  end

  private
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:user_id, :book_id)
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/create.js.erb
document.getElementById('booklist').insertAdjacentHTML("beforeend","<%= escape_javascript render @book %>") 

app/views/books/destroy.js.erb
var target_tr = document.getElementById('book-<%=@book.id%>'),
tbody_parent = document.getElementById('booklist')
tbody_parent.removeChild(target_tr) 

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Price</th>
            <th>Code</th>       
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody id="booklist">
      <%= render @books %>
    </tbody>
</table> 

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Code:</strong>
  <%= @book.code %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/show.js.erb
alert('Title: <%= @book.name %> \nContent: <%= @book.author %>') 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diego's Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'pages/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_book.html.erb
<tr id="book-<%= book.id %>">
    <td><%= book.name %></td>
    <td><%= book.author %></td>
    <td><%= book.code %></td>
    <td><%= book.price %></td>
    <td><%= link_to 'Show', book, remote: true %></td>
    <% if user_signed_in? %>
        <td><%= link_to 'Reserve', reserved_path(book_id: book.id, price: book.price), method: :post, remote: true %></td>
    <% end %>
</tr> 

app/views/pages/_form.html.erb
<%= form_with model: reservation, remote: true do |form| %>
  <%= form.select :book_id, Book.get_available_books.collect { |book| [book.namee, book.id] }, prompt: "Select a Book" %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.submit "Reserve", data: { disable_with: "Reservation in Progress"}, class: "btn btn-primary" %>
<% end %> 

app/views/pages/_make_reservation.js.erb
$('#myForm').html("<%= j render(:partial =>'pages/form', :locals => { :reservation => @reservation } ) %>");

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Diego's Bookstore</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Profile', user_books_path, remote: true, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %> 
        <li class="nav-item active">
          <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/pages/_userbooks.html.erb
<tr id="reservation-<%= reservation.id %>">
    <td><%= reservation.book.name %></td>
    <td><%= reservation.book.author %></td>
    <td><%= reservation.book.code %></td>
    <td><%= link_to 'Show', reservation.book, remote: true %></td>
    <td><%= link_to 'Buy', remote: true %></td>
    <td><%= link_to 'Remove', remove_reservation_path(id: reservation.id), remote: true, method: :delete %></td>
</tr> 

app/views/pages/index.html.erb
<div class="row" id="rowButtons">
    <div class="col">
    <%= button_to "Reserve Book", make_reservation_path, remote: true, class:"btn btn-primary", "data-toggle" => "modal", "data-target" => "#modalMakeReserve"%>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Book Code</th>
            <th>Price</th>        
        <% if user_signed_in? %>
            <th colspan="3"></th>
        <% else %>
            <th colspan="3"></th>
        <% end %>
        </tr>
    </thead>

    <tbody id="userbooklist">
        <%= render partial: "pages/book", collection: @books %>
    </tbody>
</table>

app/views/pages/index.js.erb
book_table = document.getElementById('userbooklist');
while (book_table.firstChild) {
book_table.removeChild(book_table.firstChild);
}

<% unless @books.nil? %>
    <% @books.each do |book| %>
        book_table.insertAdjacentHTML("beforeend","<%= escape_javascript render partial: "pages/book", book: book %>")
    <% end %>
<% end %> 

app/views/pages/remove_reservation.js.erb
var target_tr = document.getElementById('reservation-<%=@reservation.id%>'),
tbody_parent = document.getElementById('userbooklist')
tbody_parent.removeChild(target_tr)

app/views/pages/reserved.js.erb
var target_tr = document.getElementById('book-<%=@book.id%>'),
tbody_parent = document.getElementById('userbooklist')
tbody_parent.removeChild(target_tr) 

app/views/pages/user_books.js.erb
book_table = document.getElementById('userbooklist');
while (book_table.firstChild) {
    book_table.removeChild(book_table.firstChild);
}

<% unless @reservations.nil? %>
    <% @reservations.each do |reserved| %>
        book_table.insertAdjacentHTML("beforeend","<%= escape_javascript render "pages/userbooks", reservation: reserved %>")
    <% end %>
<% end %> 

app/views/reservation/_reservation.html.erb
<tr id="reservation-<%= reservation.id %>">
    <td><%= reservation.user_id %></td>
    <td><%= reservation.book_id %></td>
    <td><%= link_to 'Show', reservation, remote: true %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation), remote: true %></td>
    <td><%= link_to 'Remove', reservation, data: { remote: true, confirm: "Are you sure?" }, method: :delete %></td>
</tr> 

app/views/reservation/create.js.erb
document.getElementById('reservebook').insertAdjacentHTML("beforeend","<%= escape_javascript render @reservation %>") 

app/views/reservation/destroy.js.erb
var target_tr = document.getElementById('reservation-<%=@reservation.id%>'),
tbody_parent = document.getElementById('reservebook')
tbody_parent.removeChild(target_tr)

app/views/reservation/index.html.erb
<table class="table">
    <thead>
        <tr>
            <th>User_ID</th>
            <th>Book_ID</th>       
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody id="reservebook">
        <%= render @reservations %>
    </tbody>
</table> 

app/views/reservation/show.js.erb
alert('User: <%= @reservation.user.email %> \nBook: <%= @reservation.book.name %> \nAuthor: <%= @reservation.book.author %>') 